keys:
  - &pierre age1q3nnjq8695wpj7y9mdqk34pt5g4fsw7su5vslkh3ehf9vqynv4lsw8vey8
  - &pierre-nixos age1h54xc376j06l06ncj5ndv73zyl5p2j9daspxyl04hrkm5778dvhsfnyphc
creation_rules:
  - path_regex: sops/.*\.yaml$
    key_groups:
      - age:
          - *pierre
          - *pierre-nixos
