# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d88f0d6b-ab68-4657-9664-b58addf7efed";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d88f0d6b-ab68-4657-9664-b58addf7efed".device = "/dev/disk/by-uuid/d88f0d6b-ab68-4657-9664-b58addf7efed";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1AF6-8619";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d976a064-f8ba-4a71-9fd8-2538f7b9d03a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
